version: '3.6'

services:
  backend:
    build: backend
    image: registry.heroku.com/lantic-backend/web
    volumes:
      - ./backend:/app
    environment: 
      - MODE=dev
    ports:
      - 5000:5000

  # lantic-frontend:
  #   build: frontend
  #   image: ./frontend
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - 3000:3000
  #     - 35729:35729