version: '3.6'

services:
  proxy:
    image: mesudip/nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80

  backend:
    build: backend
    image: registry.heroku.com/lantic-backend/web
    volumes:
      - ./backend:/app
    environment: 
      - MODE=dev
      - VIRTUAL_HOST=lantic-backend.dev.benjaminhr.com -> :5000

  # frontend:
  #   build: frontend
  #   image: ...
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - 5000:5000